### ISSUE TITLE
To many echo statements.

### ISSUE THREAD

**Issue by andlrc** [IgorSzyporyn/automated-icon-library#3]
I stedet for at bruge:

    echo a >&3
    echo b >&3
    echo c >&3

Så brug heredoc istedet:

    cat >&3 << MY_MARKER
    a
    b
    c
    MY_MARKER

Note at `MY_MARKER` skal starte på kolonne 0.

Hele din head function, kan ca reskrives til:

    for size in 16 32 48 64; do
    cat >&3 << EOF
    .icon-16 {
      background-size: ${size}px;
      height: ${size}px;
      width: ${size}px;
    EOF
    if [ -z "$2" ]; then
    cat >&3 << EOF
      background-position: center center;
    }
    EOF
    else
    cat >&3 << EOF
      background-iamge: url('icons/${name}/sprite-${size}.png');
      background-position: 0 0;
    }
    EOF
    fi
    done

**Comment by IgorSzyporyn** [comment]
Takker!!

Min linter sagde det samme, jeg vidste bare ikke hvordan jeg skulle gøre
det :-D

Den er videreudviklet en del, og der kommer lige et push :-D

/Igor

2016-11-10 12:51 GMT+01:00 Andreas Louv <notifications@github.com>:
